[DEFAULT]
WAFER     = JS633
PIECE     = W2
LAYOUT    = Wsc@v3.1
DEVICE    = Wsc=0.9um-NNE
JJ_WIDTH  = 4e-6
JJ_LENGTH = 0.9e-6
COOLDOWN  = WFS06
FRIDGE    = vector9
FILENAME  = ${WAFER}-${PIECE}_${LAYOUT}_${DEVICE}_${COOLDOWN}
CH_FIELD_PERP = VectorMagnet - Field X
CH_BIAS   = Bias current
CH_MEAS   = VICurveTracer - VI curve
CH_GATE   = gate 15 - Source voltage
DC_AMP_GAIN = 100
R_AC_OUT  = 1e6
R_DC_OUT  = 1e6
VMIN = 0
VMAX = 500
THRESHOLD = 1e-6

[0V]
#FIELD_MIN = -3.9e-3
#FIELD_MAX = 4e-3
DATAPATH = 2024/01/Data_0115/${FILENAME}-203.hdf5

[10V]
#THRESHOLD = 16
#FIELD_MIN = -3.9e-3
#FIELD_MAX = 4e-3
DATAPATH = 2024/01/Data_0119/${FILENAME}-279.hdf5

[-4V]
#THRESHOLD = 16
#FIELD_MIN = -3.9e-3
#FIELD_MAX = 4e-3
DATAPATH = 2024/01/Data_0119/${FILENAME}-281.hdf5
