# config used by shabanipy/scripts/squid/extract_ic.py
# extracts ic data for hysteresis plots

[DEFAULT]
WAFER = JS633
PIECE = W2
LAYOUT = Wsc@v3.1
COOLDOWN = WFS06
FILENAME = ${WAFER}-${PIECE}_${LAYOUT}_${DEVICE}_${COOLDOWN}-${SCAN}.hdf5
CH_CURRENT = Bias current
CH_THRESHOLD = VICurveTracer - VI curve
THRESHOLD = 10e-4
OFFSET_NPOINTS = 3
VMIN = -100e-3
VMAX = 100e-3

[ENE]
DEVICE = Wsc=0.9um-ENE
SCAN = 198
DATAPATH = 2024/01/Data_0114/${FILENAME}
CH_IVAR = gate 21 - Source voltage

[NNE1]
DEVICE = Wsc=0.9um-NNE
SCAN = 205
DATAPATH = 2024/01/Data_0115/${FILENAME}
CH_IVAR = gate 15 - Source voltage

[NNE2]
DEVICE = Wsc=0.9um-NNE
SCAN = 206
DATAPATH = 2024/01/Data_0115/${FILENAME}
CH_IVAR = gate 15 - Source voltage
